# Basic
title: 彼岸网
subtitle: Paradise
welcome_message: 
description: 身处低谷的人看谁都像救赎 
creator: <a href="https://github.com/7emotions">@7emotions</a>

url: "https://github.com/7emotions"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: My Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: iXinian Community, description: iXinian Community, url: 'https://community.ixinian.com/'}
    - {title: Eyrunq`s Blog, description: Eyrunq`s Blog, url: 'https://qnurye.github.io/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo:
    gitment: True
    
# Social
social:
    # weibo: onevcat
    github: 7emotions
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: paradise_c@qq.com
    qq: 3393103594

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
